sezzle/sezzle-js

.gitignore
gulpfile.js
package.json

Added deployment scripts.  Will require an npm install
Adds:
```
npm run deploy-button
npm run deploy-css
```

Deployment scripts

---

sezzle.js

fix(css-load): Wait for CSS to load before DOM operation

---

sezzle.js

fix(xpath): Multiple x-path support for one page added

---

sezzle.js

https://github.com/sezzle/sezzle-js/issues/288

Options new additions rajan

---

shopify-plus/sezzleGatewayPushUp.js
shopify-plus/shopifyCheckoutObserver.js

Added JS snippets to:
a) Enable Sezzle widgets to dynamically react to changes to DOM in Shopify checkout 
b) Place Sezzle gateway option right below Credit Card

Add JS snippets for Shopify Checkout

---

gulpfile.js
sezzle.js

- IE11 support
- Geo IP endpoint hosted on our own servers (freegeoip was deprecated)
- Fingerpintjs hosted from our own CDN

Sezzle js 1.0.0

---

sezzle.js

Tested on.  We need to add a configuration too. But the algorithm is implemented and works.
https://boulderdenim.com/products/mens-athletic-fit

Fixed and tested

---

sezzle.js

A new param added for `customClasses` called `targetXPathIndex`
This value is the index value of the `config.targetXPath` where we want to put a custom class.

customClass map to targetXPath feature added

---

gulpfile.js
package.json

- package version downgraded to support the build proecess

gulp bundle bug fixed

---

.gitlab-ci.yml
gulpfile.js
package-lock.json
package.json

- Release a new version of js `npm run release -- --newversion x.x.x`
- Release a new version of css `npm run release -- --newversion x.x.x`
- Release does following
-- take and verify the new version
-- checkout to master if already not on master
-- pulls the latest from origin
-- creates a new branch with the new version number
-- update the new version number to `package.json`
-- creates a new commit with a subject recognised by deployprocess
-- push the new branch to the origin
- raise a PR from that branch to master
- To deploy we just need to merge the new branch with master

release and build process updated

---

src/helper.js
src/sezzle.js

Solves https://github.com/sezzle/sezzle-js/issues/540

540 add ignored formatted price text field

---

src/sezzle-init.js

updated window.onload to window.addEventListener to avoid load conflicts with paybright

fix for window.onload

---

src/sezzle-init.js

Solves https://github.com/sezzle/sezzle-js/issues/552

Remove load event listener

---

src/sezzle.js

See https://github.com/sezzle/sezzle-js/issues/571 for more details.

Solve issue 571

---

modals/modals-1.0.4/modal-en.html
modals/modals-1.0.4/modal-fr.html

Prefixed the common classes with szl, so they will not conflict with other sites for 1.0.4.
Updated paragraph inline styling to set the font-size.
Updated empty terms link.
Confirmed working: https://cl.ly/8d817d1b5079

Szl prefix style

---

src/sezzle.js

log with the formatted config instead of

---

modals/modals-1.0.1/modal-en.html
modals/modals-1.0.1/modal-fr.html
modals/modals-1.0.1/modal.scss
modals/modals-1.0.2/modal-en.html
modals/modals-1.0.2/modal-fr.html
modals/modals-1.0.2/modal.scss
modals/modals-1.0.3/modal-en.html
modals/modals-1.0.3/modal-fr.html
modals/modals-1.0.3/modal.scss
modals/modals-1.0.4/modal-en.html
modals/modals-1.0.4/modal-fr.html
modals/modals-1.0.4/modal.scss
modals/modals-1.0.5/modal-en.html
modals/modals-1.0.5/modal-fr.html
modals/modals-1.0.5/modal.scss
modals/modals-1.0.6/modal-en.html
modals/modals-1.0.6/modal-fr.html
modals/modals-1.0.6/modal.scss
modals/modals-1.0.7/modal-en.html
modals/modals-1.0.7/modal-fr.html
modals/modals-1.0.7/modal.scss
modals/modals-1.0.8/modal-en.html
modals/modals-1.0.8/modal-fr.html
modals/modals-1.0.8/modal.scss

timeline css changes & added link back to sezzle.com with medium and referrer tags

Changes in modals

---

src/sezzle.js

Fixes a bug where in dual widgets our modal wasn't opening. Changed the way we add event listener for modal on our widget

Dual widget sezzle modal fix

---

modals/modals-1.0.8/modal.scss
src/sezzle.js

A few JS changes to disable body scroll and maintain scroll position when modal is closed. A couple of CSS changes as well!

Modal fixes for mobile browsers and disables body scroll when modal open

---

modals/modals-1.0.8/modal.scss

Safari specific CSS added -webkit-overflow-scrolling: touch;

specific fix for safari

---

src/helper.js
src/sezzle.js

Note: modal version needs to defaulted to a min of 2.0.0 for this version to work. Also note added new themes to our widget 
Themes - dark, light, black, white, black-flat, white-flat, grayscale

after changing logo urls and adding new themes

---

modals/README.md
modals/modals-2.0.0/modal.scss

Update to mobile css

---

src/helper.js
src/sezzle.js

adds line height feature into the sezzle js

after adding line height

---

src/sezzle.js

Fixes api success check fail on some merchants

JIRA WID-77: Fixes issue with API success check on few merchants

---

package-lock.json
package.json

Fixes XmlHTTPRequest.DONE not evaluating to 4 on some merchants

bumped js version to: 6.0.2

---

README.md
src/sezzle.js

Changes Made
1 Readme file updated
2 check for multi buttons
3. removed parentElement error on product pages

Wid 81 sezzle checkout button

---

modals/modals-2.0.0/modal-de.html
modals/modals-2.0.0/modal-en.html
modals/modals-2.0.0/modal-fr.html
modals/modals-2.0.0/modal.scss
modals/modals-2.0.1/modal-de.html
modals/modals-2.0.1/modal-en.html
modals/modals-2.0.1/modal-fr.html
modals/modals-2.0.1/modal.scss
package.json
src/ShopifyTracker/tracker.js
src/classBased/modal.js
src/classBased/renderAwesomeSezzle.js
src/classBased/sezzleConfig.js
src/classBased/sezzleDOMFunctions.js
styles/global.scss

Wid 251 eu price handling

---

src/classBased/modal.js
src/classBased/renderAwesomeSezzle.js

Changelog:
-> Dynamic modal rendering for other vendors
-> Modal scroll position restore for other vendors

Resolves Jira WID-269

---

src/ShopifyTracker/tracker.js
src/classBased/sezzle.js
src/classBased/sezzleConfig.js
src/classBased/utils.js
widget-options.md

Disable widget tracking iframe

Wid 265 remove tracking

---

gulpfile.js

- Push css, widget and button version to EU widget server as a part of gulp deploy task

EUDEV-343 post configs to eu widget server

---

gulpfile.js

- The gulp tasks seems to be failing because of not marking `done()`. This fix is to try out if that's the case, on local, the task runs without any issue but fails on CI. 
- A flag `--local` is added for local testing in which case the API sends the request to `http://localhost:12121`
- Gulp task for uploading data to Widget server is made parallel for US and EU

EUDEV-350 fix for deploy failure with gulp task

---

modals/modals-2.0.8/modal-de-DE.html
modals/modals-2.0.8/modal-en-GB.html
package-lock.json
package.json
release_history.json

bumped modal version to: 2.0.8

---

src/classBased/modal.js

added underscores for this.modalNode.ariaModal and this.modalNode.ariaLabel

WID-589 added underscores for this.modalNode.ariaModal and this.modalNode.ariaLabel

---

package-lock.json
package.json

bumped js version to: 21.6.4

---

modals/modals-2.0.8/modal-de-DE.html
modals/modals-2.0.8/modal.scss

Adapt German copy for 2.0.8 modal

EUDEV-1008 adapt german copy for modal

---

modals/modals-2.0.8/modal-de-DE.html
modals/modals-2.0.8/modal-en-GB.html
modals/modals-2.0.8/modal-es-ES.html
modals/modals-2.0.8/modal-fr-FR.html
modals/modals-2.0.8/modal.scss
src/classBased/language.js

Update fr-FR widget copy.
Add modal font-family specificity.

EUDEV-1100 update french widget translation
